[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pytest-udemy" # PyPi prefers dashes so replace underscores with dashes
version = "0.0.2"
description = "Sort plugin for Pytest"

[project.entry-points.pytest11]
sort_name = "pytest_sort" # sort_name can be any name, the main thing is the entry point points to the plugin `pytest_sort` 

[tool.flit.module]
name = "pytest_sort" # module must match plugin py file so use '_'
