[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "the_full_name_of_your_plugin_as_listed_in_PyPi" 
# Your own details here...
authors = [{ name = "Craig West", email = "craig@example.com" }]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License", "Framework :: Pytest"]
version = "0.0.2"
description = "Sort plugin for Pytest"
dependencies = ["pytest>=6.2.0"]
requires-python = ">=3.7"


[project.urls]
# Your own Repo URL
Home = "https://github.com/python-test-engineer/Udemy-PyTest"

[project.entry-points.pytest11]
# Entry point of your package. It may be different if you have you entry point in a different location
sort_name = "pytest_sort"

[project.optional-dependencies]
# optional dependencies
test = ["tox"]
# 
[tool.flit.module]
# where flit needs to look for the plugin
name = "pytest_sort" 
